### ISSUE TITLE
Module 1 (Content tracking with DataLad) ready for review

### ISSUE THREAD

**Issue by mslw** [psychoinformatics-de/rdm-course#12]
From my point of view, Module 1 is ready, but I would appreciate a review.

The aim of this module is to:
- introduce the basic DataLad commands for local workflow (`help`, `create`, `save`, `run`, `status` + `git log`/`tig`)
- introduce the idea of version control along the way
- highlight the distinction between text & binary (annexed and non-annexed)

The other target I was going for was to do things one step at a time to build familiarity with these basic commands. So first download a file manually, and only then show `download-url` even though that basically does the same thing. First save the output with `datalad save` and then do `datalad run` etc. Curious to know opinions whether I achieved this target, and whether the approach works.

Keep in mind that the examples assume having python with pillow library installed, see [Setup](https://psychoinformatics-de.github.io/rdm-course/setup.html)

I would appreciate comments regarding:
- flow & suitability for inexperienced audience
- time feasibility
- content selection: omissions or unnecessary details
- factual mistakes
- any other details that come to your mind

Course website: https://psychoinformatics-de.github.io/rdm-course/
File content in _episodes folder.

**Comment by adswa** [comment]
I will start to take a look now. In practice, it would be easiest if this could somehow be a PR where we can just put comments into the sources, but thats for future additions. Unless  you have  a different preference where you want comments, I'll put them right here into the issue

**Comment by adswa** [comment]
### Introduction

- I like the idea that it introduces the contents of the course in a use-case oriented way.
- My worry is that the wealth of use cases it may be a bit too abstract for people that have no idea about Git. I wonder whether a slight change in narrative tone could help to make it easier to think into those situations - instead of telling people to imagine themselves in a certain situation (which is a bit extra cognitive overhead, also with the maybe's in brackets), introduce a fictive character that is in the situation instead. This way, they can focus on imagining the use case without yet having to see themselves in it. Here is an example what I mean: https://jugit.fz-juelich.de/inm7/training/htcondor#meet-bob-and-alice

### Setup

- maybe include a link to the setup section, just to be sure. Especially probably the part with the virtualenv, because people that may have skipped the setup or came late could get confused.

### Objective

I think there is some overlap with the introduction. Maybe it could be merged into the Introductions last paragraph. Then, Setup and How to use DataLad would also follow each other more smoothly

### Version control

- Just a side question, but why is the wget command so complex? The ``--directory-prefix`` flag isn't even part of the man page on my system and shouldn't be necessary when you created the directories beforehand, right?. Also, maybe its useful to add ``-q`` for quiet?
- unless you want to build the lessons on file naming on that file name (``derek-oyen-3Xd5j9-drDA-unsplash.jpg``), wouldn't it make sense to rename the image to something nicer? (``-o``)

### Data processing
- you could datalad-download-url the processing script, too, if you want

### General

- Do we have the technical means to easily include a glossary into the lesson? Some of the terms would benefit from a link to quick definition overview
- I wonder if it is useful  to hide the "output" shells until someone clicks on their corresponding command bash (a bit like the toggles in the exercise, but different color)

**Comment by adswa** [comment]
The dev note also says ``binary vs text distinction`` but there is only a single sentence on that distinction. Maybe you can foreshadow or link the second episode as a place where more light on text versus binary files will be shed?

**Comment by mslw** [comment]
Thanks for all the comments! Very much appreciated. I'll introduce changes or make more detailed comments later on.

**Comment by mslw** [comment]
Detailed answers and related action items below. Changes bundled in the PR linked above.

### Introduction
> - My worry is that the wealth of use cases it may be a bit too abstract for people that have no idea about Git. I wonder whether a slight change in narrative tone could help to make it easier to think into those situations - instead of telling people to imagine themselves in a certain situation (which is a bit extra cognitive overhead, also with the maybe's in brackets), introduce a fictive character that is in the situation instead. This way, they can focus on imagining the use case without yet having to see themselves in it. Here is an example what I mean: https://jugit.fz-juelich.de/inm7/training/htcondor#meet-bob-and-alice

This is an interesting perspective - I usually thought the other way round, ie. "imagine that you..." seemed more natural to me. But maybe the current introduction does look clunky. Rewrite will require some creativity, so I'm putting it as a to-do item for myself, for when I have the energy to do so.
- [x] rewrite the introduction

### Setup
> maybe include a link to the setup section, just to be sure. Especially probably the part with the virtualenv, because people that may have skipped the setup or came late could get confused

Agree - for the first workshop we will provide the environment, but for the materials to live alone this needs to be clear.
- [x] add link to setup

### Objective
> I think there is some overlap with the introduction. Maybe it could be merged into the Introductions last paragraph. Then, Setup and How to use DataLad would also follow each other more smoothly

Agree. At first I was worried that the necessary git setup steps will detract from the narrative. But your proposed order works best, and I adjusted the text.
- [x] merge Introduction & Objective

### Version control
> - Just a side question, but why is the wget command so complex? The --directory-prefix flag isn't even part of the man page on my system and shouldn't be necessary when you created the directories beforehand, right?. Also, maybe its useful to add -q for quiet?

FTR, the combination of `--directory-prefix` ("the directory where all other files and subdirectories will be saved to") and `--content disposition` was the best way I found (thx StackOverflow) to put the output in a given directory and keep the original file name (the Unsplash links do not contain the file name, there is some processing of the request on their side. However, this was unnecessary in light of your suggestion below. Using quiet mode is also a good idea, but I don't think it's necessary.

> - unless you want to build the lessons on file naming on that file name (derek-oyen-3Xd5j9-drDA-unsplash.jpg), wouldn't it make sense to rename the image to something nicer? (-o)

Good point, at first I wanted to keep the original names, but they become burdensome later on. I simplified all file names to `<penguin species>_<number>.jpg` and changed the command to `wget -O inputs/images/chinstrap_01.jpg <url>` (fun fact - `wget` uses capital O for output, but luckily so does `datalad download-url`). This avoids copying, renaming, changing directory, and keeps everything in one simple command. Thanks for pointing this out!

- [x] Simplify file names and wget command

### Data processing

> - you could datalad-download-url the processing script, too, if you want

True, but maybe better to keep things separate at this stage. Probably a good remark to include.

### General

> - Do we have the technical means to easily include a glossary into the lesson? Some of the terms would benefit from a link to quick definition overview

There's is a reference in the lesson template, accessible (in rendered html) under Extras in the top bar, and kept in `reference.md` (in markdown source). So far we kept the content from the shell swcarpentry lesson, and I didn't have the power to tackle it.
- [ ] maybe add some terms to the reference?

> - I wonder if it is useful to hide the "output" shells until someone clicks on their corresponding command bash (a bit like the toggles in the exercise, but different color)

Looking at the "special blockquotes" already provided by the lesson template, only `.solution` is foldable. Maybe new ones can be defined, but I don't know. I don't mind having outputs visible from the outset though.

**Comment by mslw** [comment]
Once again thank you for the suggestions, I think I was successful in introducing them and the end result is improved. I'm closing this issue, but feel free to reopen if something new comes up.
